schema: arena.task/v0alpha1
name: task:openspiel-connect-four@0.4
adapter: openspiel
env: openspiel://connect_four
interaction: aec
version: open_spiel-2.0.1:connect_four
packaging:
  kind: openspiel
digest: sha256:9b6ffe588b8bafdf7fbde93aeb22c56b8126c91d2f556463b77886a00959a45b
