schema: rlx.task/v0alpha1
name: task:openspiel-kuhn-poker@0.5
adapter: openspiel
env: openspiel://kuhn_poker
interaction: aec
version: open_spiel-2.0.1:kuhn_poker
packaging:
  kind: openspiel
digest: sha256:c283caeb446143337077c726927e8fed84a32c1be533bdfde2f66a891c36dd48
