schema: arena.task/v0alpha1
name: task:openspiel-tic-tac-toe@0.3
adapter: openspiel
env: openspiel://tic_tac_toe
interaction: aec
version: open_spiel-2:tic_tac_toe
packaging:
  kind: openspiel
digest: sha256:9dd9987a8bd596acb4e0f534750287ba9e4a1475061b46c31563f507b418d218
