schema: arena.task/v0alpha1
name: task:openspiel-matrix-rps@0.5
adapter: openspiel
env: openspiel://matrix_rps
interaction: parallel
version: open_spiel-2.0.1:matrix_rps
packaging:
  kind: openspiel
digest: sha256:450c00cd8775494ea5f769141c476d1182f57f5e83aecb65b2c9ed3a02e495d5
