schema: rlx.task/v0alpha1
name: task:openspiel-connect-four@0.4
adapter: openspiel
env: openspiel://connect_four
interaction: aec
version: open_spiel-2.0.1:connect_four
packaging:
  kind: openspiel
digest: sha256:c81157a644c99563d87e4de1f0752ccf9c61905f300dd56ee67e3c048d90184e
