schema: arena.task/v0alpha1
name: task:pettingzoo-classic-rps@1.0
adapter: pettingzoo-parallel
env: classic/rps_v2
interaction: parallel
version: pettingzoo
packaging:
  kind: pettingzoo_wrappers
config:
  max_cycles: 1
digest: sha256:29a74779322b86273704a56b617029524ea2f03d26bdd16a9e2e01592652d017
